### ISSUE TITLE
[FEAT] 댓글 좋아요 취소 구현

### ISSUE THREAD

**Issue by levhyun** [TW00D/letsgo-api-mini#37]
## 어떤 기능입니까?
댓글 좋아요 취소

## TODO
- [ ] 서비스 작성
- [ ] 컨트롤러 작성

## 데드라인
2024/03/23 11:00 ~ 2024/03/26 23:00

## 기타 사항
내용 없음

**Comment by fullgukbap** [comment]
2024.04.03 기준으로 12:14 PM issue를 해결했으니 본 issue는 철회하겠습니다.
