### ISSUE TITLE
[FEAT] 댓글 삭제 구현

### ISSUE THREAD

**Issue by levhyun** [TW00D/letsgo-api-mini#38]
## 어떤 기능입니까?
댓글 삭제

## TODO
- [ ] 서비스 작성
- [ ] 컨트롤러 작성

## 데드라인
2024/03/23 11:00 ~ 2024/03/26 23:00

## 기타 사항
내용 없음

**Comment by fullgukbap** [comment]
2024.04.03 6:18 PM 기준으로 구현했기에 철회하겠습니다.
